# Use uma imagem base com Node.js
FROM node:14

# Define o diretório de trabalho
WORKDIR /app

# Copie os arquivos de requisitos e instale as dependências
COPY package.json package-lock.json ./
RUN npm install

# Copie o restante do código da aplicação
COPY . .

# Exponha a porta que a aplicação vai rodar
EXPOSE 5000

# Comando para iniciar a aplicação
CMD ["npm", "start"]
